version: '3'

volumes:
  pg_data_kat:
  static_volume:
  media_volume:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kat:/var/lib/postgresql/data

  backend:
    image: jonydas/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    image: jonydas/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static

  gateway:
    image: jonydas/kittygram_gateway
    volumes:
      - static_volume:/static
      - media_volume:/media
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend